import { GetServerSideProps } from 'next';
import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';

import { Hero, Slider, Brands, Collection } from '../components';
// import popularMovies from '../api/popularMovies.json';
// import popularShows from '../api/popularShows.json';
// import topRatedMovies from '../api/topRatedMovies.json';
// import topRatedShows from '../api/topRatedShows.json';

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  const [
    popularMoviesRes,
    popularShowsRes,
    top_ratedMoviesRes,
    top_ratedShowsRes,
  ] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
  ]);
  const [popularMovies, popularShows, topRatedMovies, topRatedShows] =
    await Promise.all([
      popularMoviesRes.json(),
      popularShowsRes.json(),
      top_ratedMoviesRes.json(),
      top_ratedShowsRes.json(),
    ]);

  return {
    props: {
      session,
      popularMovies: popularMovies.results,
      popularShows: popularShows.results,
      topRatedMovies: topRatedMovies.results,
      topRatedShows: topRatedShows.results,
    },
  };
};

export default function Home({
  popularMovies,
  popularShows,
  topRatedMovies,
  topRatedShows,
}: any) {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Disney+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session ? (
        <Hero />
      ) : (
        <main
          className="relative min-h-screen after:bg-home after:bg-center
        after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]"
        >
          <Slider />
          <Brands />
          <Collection movies title="Popular Movies" results={popularMovies} />
          <Collection
            movies
            title="Top Rated Movies"
            results={topRatedMovies}
          />
          <Collection title="Popular Shows" results={popularShows} />
          <Collection title="Top Rated Shows" results={topRatedShows} />
        </main>
      )}
    </>
  );
}
